name: vqa-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - pyngrok
      - transformers
      - torch
      - torchvision
      - pillow
      - python-dotenv
      - nest-asyncio
